export interface TemplateEntry {
  slug: string;
  title: string;
  category: string;
}

export const TEMPLATES: TemplateEntry[] = [
  { slug: 'abandoned-places', title: 'Abandoned Places', category: 'other' },
  { slug: 'adhd-tips', title: 'Adhd Tips', category: 'other' },
  { slug: 'ai-voice-cloning', title: 'Ai Voice Cloning', category: 'other' },
  { slug: 'alien-worlds', title: 'Alien Worlds', category: 'other' },
  { slug: 'anime-vibes', title: 'Anime Vibes', category: 'other' },
  { slug: 'apex-billionnaire-tax-structures', title: 'Apex Billionnaire Tax Structures', category: 'finance' },
  { slug: 'architecture-that-smooth', title: 'Architecture That Smooth', category: 'other' },
  { slug: 'baby-tiny-wins', title: 'Baby Tiny Wins', category: 'other' },
  { slug: 'ballet-moves', title: 'Ballet Moves', category: 'health' },
  { slug: 'balloons-are-us', title: 'Balloons Are Us', category: 'other' },
  { slug: 'barbers-cut', title: 'Barbers Cut', category: 'creative' },
  { slug: 'barber-shop-luxury', title: 'Barber Shop Luxury', category: 'creative' },
  { slug: 'bingo-time', title: 'Bingo Time', category: 'other' },
  { slug: 'basketball-life', title: 'Basketball Life', category: 'health' },
  { slug: 'beach-glow', title: 'Beach Glow', category: 'other' },
  { slug: 'bear-country', title: 'Bear Country', category: 'other' },
  { slug: 'bee-stitch', title: 'Bee Stitch', category: 'other' },
  { slug: 'biology-upgrade-engine', title: 'Biology Upgrade Engine', category: 'other' },
  { slug: 'brand-mood', title: 'Brand Mood', category: 'other' },
  { slug: 'business-tax-strategy-engineers', title: 'Business Tax Strategy Engineers', category: 'finance' },
  { slug: 'candle-light-the-mood', title: 'Candle Light The Mood', category: 'services' },
  { slug: 'canvas-current', title: 'Canvas Current', category: 'other' },
  { slug: 'card-decks', title: 'Card Decks', category: 'other' },
  { slug: 'calendars-unite', title: 'Calendars Unite', category: 'other' },
  { slug: 'carpet-palace', title: 'Carpet Palace', category: 'services' },
  { slug: 'cars-beyond', title: 'Cars Beyond', category: 'other' },
  { slug: 'casino-time', title: 'Casino Time', category: 'other' },
  { slug: 'celebrities-around', title: 'Celebrities Around', category: 'other' },
  { slug: 'ceramic-factory', title: 'Ceramic Factory', category: 'other' },
  { slug: 'christmas-home-glow', title: 'Christmas Home Glow', category: 'services' },
  { slug: 'cinema-rush', title: 'Cinema Rush', category: 'other' },
  { slug: 'cinematic-caves', title: 'Cinematic Caves', category: 'other' },
  { slug: 'circus-is-here', title: 'Circus Is Here', category: 'other' },
  { slug: 'clean-sweep', title: 'Clean Sweep', category: 'services' },
  { slug: 'clear-ledger-bookkeeping', title: 'Clear Ledger Bookkeeping', category: 'finance' },
  { slug: 'clean-slate-digital', title: 'Clean Slate Digital', category: 'other' },
  { slug: 'clip-scale-studio', title: 'Clip Scale Studio', category: 'other' },
  { slug: 'close-rate-tax', title: 'Close Rate Tax', category: 'finance' },
  { slug: 'coffee-please', title: 'Coffee Please', category: 'food/bev' },
  { slug: 'comedy-clubs-open', title: 'Comedy Clubs Open', category: 'other' },
  { slug: 'construction-junction', title: 'Construction Junction', category: 'services' },
  { slug: 'cornhole-fun', title: 'Cornhole Fun', category: 'health' },
  { slug: 'cosmic-visuals', title: 'Cosmic Visuals', category: 'other' },
  { slug: 'cosmetic-glam-vibe', title: 'Cosmetic Glam Vibe', category: 'creative' },
  { slug: 'creator-frame', title: 'Creator Frame', category: 'other' },
  { slug: 'credit-repair', title: 'Credit Repair', category: 'finance' },
  { slug: 'criminal-attorney', title: 'Criminal Attorney', category: 'legal' },
  { slug: 'criminal-defense-attorney', title: 'Criminal Defense Attorney', category: 'legal' },
  { slug: 'criminal-tax-defense', title: 'Criminal Tax Defense', category: 'finance' },
  { slug: 'daily-prompts', title: 'Daily Prompts', category: 'other' },
  { slug: 'deep-sea-diving', title: 'Deep Sea Diving', category: 'other' },
  { slug: 'demolition-services', title: 'Demolition Services', category: 'services' },
  { slug: 'dental-office-with-glow', title: 'Dental Office With Glow', category: 'services' },
  { slug: 'dessert-ebook', title: 'Dessert Ebook', category: 'food/bev' },
  { slug: 'digital-art-vault', title: 'Digital Art Vault', category: 'other' },
  { slug: 'digital-event-engine', title: 'Digital Event Engine', category: 'other' },
  { slug: 'digital-product-experience', title: 'Digital Product Experience', category: 'other' },
  { slug: 'digital-product-experience-v2', title: 'Digital Product Experience V2', category: 'other' },
  { slug: 'digital-stickers', title: 'Digital Stickers', category: 'other' },
  { slug: 'dog-memorial-ecards', title: 'Dog Memorial Ecards', category: 'other' },
  { slug: 'dogs-who-are-calm', title: 'Dogs Who Are Calm', category: 'other' },
  { slug: 'doll-house', title: 'Doll House', category: 'services' },
  { slug: 'double-dutch-bunch', title: 'Double Dutch Bunch', category: 'other' },
  { slug: 'drone-display', title: 'Drone Display', category: 'other' },
  { slug: 'elegant-french-restraurant', title: 'Elegant French Restraurant', category: 'other' },
  { slug: 'entities-tax-structured-right', title: 'Entities Tax Structured Right', category: 'finance' },
  { slug: 'event-posters', title: 'Event Posters', category: 'other' },
  { slug: 'exit-planners', title: 'Exit Planners', category: 'finance' },
  { slug: 'facing-tax-audit', title: 'Facing Tax Audit', category: 'finance' },
  { slug: 'facing-the-irs', title: 'Facing The Irs', category: 'finance' },
  { slug: 'fame-fabulous', title: 'Fame Fabulous', category: 'other' },
  { slug: 'fashion-centric', title: 'Fashion Centric', category: 'creative' },
  { slug: 'fast-food-tastes-good', title: 'Fast Food Tastes Good', category: 'food/bev' },
  { slug: 'fire-guard-prevention-services', title: 'Fire Guard Prevention Services', category: 'services' },
  { slug: 'fit-body-fit-mind', title: 'Fit Body Fit Mind', category: 'health' },
  { slug: 'football-time', title: 'Football Time', category: 'health' },
  { slug: 'frame-depot', title: 'Frame Depot', category: 'other' },
  { slug: 'free-fall-fever', title: 'Free Fall Fever', category: 'other' },
  { slug: 'furniture-house', title: 'Furniture House', category: 'services' },
  { slug: 'furniture-staging', title: 'Furniture Staging', category: 'services' },
  { slug: 'game-sphere', title: 'Game Sphere', category: 'other' },
  { slug: 'gardening-season', title: 'Gardening Season', category: 'other' },
  { slug: 'ghost-spectre-studios', title: 'Ghost Spectre Studios', category: 'other' },
  { slug: 'gift-giving-surprise', title: 'Gift Giving Surprise', category: 'other' },
  { slug: 'global-tax', title: 'Global Tax', category: 'finance' },
  { slug: 'graphic-stickers', title: 'Graphic Stickers', category: 'other' },
  { slug: 'guitar-zero', title: 'Guitar Zero', category: 'other' },
  { slug: 'hair-inspiration', title: 'Hair Inspiration', category: 'creative' },
  { slug: 'hair-ology', title: 'Hair Ology', category: 'creative' },
  { slug: 'halloween-nights', title: 'Halloween Nights', category: 'other' },
  { slug: 'happy-paw-ter', title: 'Happy Paw Ter', category: 'other' },
  { slug: 'haunted-houses', title: 'Haunted Houses', category: 'services' },
  { slug: 'height-lovers', title: 'Height Lovers', category: 'other' },
  { slug: 'high-income-low-tax', title: 'High Income Low Tax', category: 'finance' },
  { slug: 'higher-altitude-wallpaper', title: 'Higher Altitude Wallpaper', category: 'other' },
  { slug: 'holiday-calendars', title: 'Holiday Calendars', category: 'other' },
  { slug: 'home-furnishings-galore', title: 'Home Furnishings Galore', category: 'services' },
  { slug: 'home-sync', title: 'Home Sync', category: 'services' },
  { slug: 'horizon-tax-forecast', title: 'Horizon Tax Forecast', category: 'finance' },
  { slug: 'horses-free', title: 'Horses Free', category: 'other' },
  { slug: 'house-sitters', title: 'House Sitters', category: 'services' },
  { slug: 'ice-sculture-smooth', title: 'Ice Sculture Smooth', category: 'other' },
  { slug: 'immersive-lab-studio', title: 'Immersive Lab Studio', category: 'other' },
  { slug: 'innocent-spouse-relief-starts-now', title: 'Innocent Spouse Relief Starts Now', category: 'legal' },
  { slug: 'irs-crisis', title: 'Irs Crisis', category: 'finance' },
  { slug: 'irs-ligitation', title: 'Irs Ligitation', category: 'finance' },
  { slug: 'irs-installment-agreement-path', title: 'Irs Installment Agreement Path', category: 'finance' },
  { slug: 'irs-penalties-stopped', title: 'Irs Penalties Stopped', category: 'finance' },
  { slug: 'irs-transcript-clarity', title: 'Irs Transcript Clarity', category: 'finance' },
  { slug: 'jet-sky-adventures', title: 'Jet Sky Adventures', category: 'other' },
  { slug: 'jewelry-glam', title: 'Jewelry Glam', category: 'creative' },
  { slug: 'kitchen-tips', title: 'Kitchen Tips', category: 'food/bev' },
  { slug: 'lake-wallpapers', title: 'Lake Wallpapers', category: 'other' },
  { slug: 'language-translation', title: 'Language Translation', category: 'services' },
  { slug: 'las-vegas-experience', title: 'Las Vegas Experience', category: 'services' },
  { slug: 'life-insurance-benefits', title: 'Life Insurance Benefits', category: 'finance' },
  { slug: 'luxe-picnic', title: 'Luxe Picnic', category: 'other' },
  { slug: 'makeup-mile', title: 'Makeup Mile', category: 'creative' },
  { slug: 'mansion-top', title: 'Mansion Top', category: 'services' },
  { slug: 'millionniare-tax-insights', title: 'Millionniare Tax Insights', category: 'finance' },
  { slug: 'mini-home', title: 'Mini Home', category: 'services' },
  { slug: 'motorcyle-touring', title: 'Motorcyle Touring', category: 'other' },
  { slug: 'muscle-cars', title: 'Muscle Cars', category: 'other' },
  { slug: 'mystery-reveal-packages', title: 'Mystery Reveal Packages', category: 'other' },
  { slug: 'mystic-glow-wallpapers', title: 'Mystic Glow Wallpapers', category: 'other' },
  { slug: 'neuro-peak', title: 'Neuro Peak', category: 'other' },
  { slug: 'new-moms', title: 'New Moms', category: 'other' },
  { slug: 'notary-today', title: 'Notary Today', category: 'legal' },
  { slug: 'notary-ready', title: 'Notary Ready', category: 'legal' },
  { slug: 'orb-flow-entertainment', title: 'Orb Flow Entertainment', category: 'other' },
  { slug: 'party-themes', title: 'Party Themes', category: 'other' },
  { slug: 'payroll-times', title: 'Payroll Times', category: 'finance' },
  { slug: 'perfume-scent', title: 'Perfume Scent', category: 'creative' },
  { slug: 'photographers-delight', title: 'Photographers Delight', category: 'other' },
  { slug: 'planet-portal', title: 'Planet Portal', category: 'other' },
  { slug: 'planet-pulse', title: 'Planet Pulse', category: 'other' },
  { slug: 'plot-twist', title: 'Plot Twist', category: 'other' },
  { slug: 'prompts-for-ai', title: 'Prompts For Ai', category: 'other' },
  { slug: 'property-tax-advantage', title: 'Property Tax Advantage', category: 'finance' },
  { slug: 'quarterly-tax-planning-experts', title: 'Quarterly Tax Planning Experts', category: 'finance' },
  { slug: 'quilt-sewing-maker', title: 'Quilt Sewing Maker', category: 'other' },
  { slug: 'rainbow-experience', title: 'Rainbow Experience', category: 'other' },
  { slug: 'ramen-for-me', title: 'Ramen For Me', category: 'food/bev' },
  { slug: 'realtor-listing', title: 'Realtor Listing', category: 'services' },
  { slug: 'retail-flip-sense', title: 'Retail Flip Sense', category: 'services' },
  { slug: 'retire-smart', title: 'Retire Smart', category: 'finance' },
  { slug: 'roofing-experts', title: 'Roofing Experts', category: 'services' },
  { slug: 'sales-tax-nexus', title: 'Sales Tax Nexus', category: 'finance' },
  { slug: 'salt-strategic-planner', title: 'Salt Strategic Planner', category: 'finance' },
  { slug: 'screen-visual-gallery', title: 'Screen Visual Gallery', category: 'other' },
  { slug: 'segway-tours', title: 'Segway Tours', category: 'other' },
  { slug: 'shark-attack', title: 'Shark Attack', category: 'other' },
  { slug: 'sign-language-translation', title: 'Sign Language Translation', category: 'services' },
  { slug: 'signal-and-scale', title: 'Signal And Scale', category: 'other' },
  { slug: 'sky-rise-balloon-adventure', title: 'Sky Rise Balloon Adventure', category: 'other' },
  { slug: 'sneaker-ecards', title: 'Sneaker Ecards', category: 'other' },
  { slug: 'soccer-wins', title: 'Soccer Wins', category: 'health' },
  { slug: 'social-influencer', title: 'Social Influencer', category: 'other' },
  { slug: 'space-layer-augmented-reality', title: 'Space Layer Augmented Reality', category: 'other' },
  { slug: 'spinning-cards', title: 'Spinning Cards', category: 'other' },
  { slug: 'stage-light-it-up', title: 'Stage Light It Up', category: 'other' },
  { slug: 'stamps-in-digital', title: 'Stamps In Digital', category: 'other' },
  { slug: 'stars-abound', title: 'Stars Abound', category: 'other' },
  { slug: 'stay-scape', title: 'Stay Scape', category: 'other' },
  { slug: 'sticker-drops', title: 'Sticker Drops', category: 'other' },
  { slug: 'storage-here', title: 'Storage Here', category: 'services' },
  { slug: 'street-racing-cars', title: 'Street Racing Cars', category: 'other' },
  { slug: 'stunt-core', title: 'Stunt Core', category: 'other' },
  { slug: 'supercars', title: 'Supercars', category: 'other' },
  { slug: 'super-flyers', title: 'Super Flyers', category: 'other' },
  { slug: 'sunsets-spectacular', title: 'Sunsets Spectacular', category: 'other' },
  { slug: 'surfing-lounge', title: 'Surfing Lounge', category: 'health' },
  { slug: 'tarot-card-arcana', title: 'Tarot Card Arcana', category: 'other' },
  { slug: 'tattoos-galore', title: 'Tattoos Galore', category: 'other' },
  { slug: 'tax-attorney-services', title: 'Tax Attorney Services', category: 'finance' },
  { slug: 'tax-command-advisory', title: 'Tax Command Advisory', category: 'finance' },
  { slug: 'tax-credits-are-yours', title: 'Tax Credits Are Yours', category: 'finance' },
  { slug: 'tax-planning-today', title: 'Tax Planning Today', category: 'finance' },
  { slug: 'tax-preparation-now', title: 'Tax Preparation Now', category: 'finance' },
  { slug: 'tax-relief', title: 'Tax Relief', category: 'finance' },
  { slug: 'taxes-genz', title: 'Taxes Genz', category: 'finance' },
  { slug: 'tea-anyone', title: 'Tea Anyone', category: 'food/bev' },
  { slug: 'tea-dip-sip', title: 'Tea Dip Sip', category: 'food/bev' },
  { slug: 'the-daily-current', title: 'The Daily Current', category: 'other' },
  { slug: 'theme-ride-verse', title: 'Theme Ride Verse', category: 'other' },
  { slug: 'track-racing', title: 'Track Racing', category: 'health' },
  { slug: 'travel-meal-plan', title: 'Travel Meal Plan', category: 'food/bev' },
  { slug: 'tree-lovers-delight', title: 'Tree Lovers Delight', category: 'other' },
  { slug: 'trending-pulse', title: 'Trending Pulse', category: 'other' },
  { slug: 'trust-and-estate-planners', title: 'Trust And Estate Planners', category: 'other' },
  { slug: 'unplug-retreat', title: 'Unplug Retreat', category: 'other' },
  { slug: 'viral-moment', title: 'Viral Moment', category: 'other' },
  { slug: 'virtual-persona-management', title: 'Virtual Persona Management', category: 'other' },
  { slug: 'visual-strike-stickers', title: 'Visual Strike Stickers', category: 'other' },
  { slug: 'vita-drip-mobile', title: 'Vita Drip Mobile', category: 'services' },
  { slug: 'wall-paintings', title: 'Wall Paintings', category: 'services' },
  { slug: 'watches-superb', title: 'Watches Superb', category: 'services' },
  { slug: 'water-adventures', title: 'Water Adventures', category: 'other' },
  { slug: 'wealth-shield-tax-strategies', title: 'Wealth Shield Tax Strategies', category: 'finance' },
  { slug: 'wedding-upgrade', title: 'Wedding Upgrade', category: 'other' },
  { slug: 'weekend-adventure', title: 'Weekend Adventure', category: 'other' },
  { slug: 'whale-breach', title: 'Whale Breach', category: 'other' },
  { slug: 'wild-weather', title: 'Wild Weather', category: 'other' },
  { slug: 'wild-weather-v2', title: 'Wild Weather V2', category: 'other' },
  { slug: 'windline-sailing', title: 'Windline Sailing', category: 'other' },
  { slug: 'world-cuisine', title: 'World Cuisine', category: 'food/bev' },
  { slug: 'world-traveler', title: 'World Traveler', category: 'other' },
  { slug: 'written-in-stone', title: 'Written In Stone', category: 'other' },
  { slug: 'work-space-flow', title: 'Work Space Flow', category: 'other' },
  { slug: 'zoo-scape', title: 'Zoo Scape', category: 'other' },
];

const CATEGORY_LABELS: Record<string, string> = {
  health: 'health & wellness',
  finance: 'finance',
  legal: 'legal',
  'food/bev': 'food & beverage',
  creative: 'creative',
  services: 'services',
  other: 'business',
};

export function getCategoryLabel(category: string): string {
  return CATEGORY_LABELS[category] ?? 'business';
}
