-- Seed WLVLP templates — generated 2026-03-30T22:23:42.290Z

INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('adhd-tips', 'Adhd Tips', 'health', 'available', 0, 99, '/sites/adhd-tips/adhd-tips.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('alien-worlds', 'Alien Worlds', 'other', 'available', 0, 99, '/sites/alien-worlds/alien-worlds.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('anime-vibes', 'Anime Vibes', 'creative', 'available', 0, 99, '/sites/anime-vibes/anime-vibes.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('architecture-that-smooth', 'Architecture That Smooth', 'other', 'available', 0, 99, '/sites/architecture-that-smooth/architecture-that-smooth.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('baby-tiny-wins', 'Baby Tiny Wins', 'health', 'available', 0, 99, '/sites/baby-tiny-wins/baby-tiny-wins.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('ballet-moves', 'Ballet Moves', 'creative', 'available', 0, 99, '/sites/ballet-moves/ballet-moves.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('balloons-are-us', 'Balloons Are Us', 'other', 'available', 0, 99, '/sites/balloons-are-us/balloons-are-us.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('barber-shop-luxury', 'Barber Shop Luxury', 'services', 'available', 0, 99, '/sites/barber-shop-luxury/barber-shop-luxury.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('barbers-cut', 'Barbers Cut', 'services', 'available', 0, 99, '/sites/barbers-cut/barbers-cut.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('beach-glow', 'Beach Glow', 'other', 'available', 0, 99, '/sites/beach-glow/beach-glow.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('bear-country', 'Bear Country', 'other', 'available', 0, 99, '/sites/bear-country/bear-country.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('bee-stitch', 'Bee Stitch', 'health', 'available', 0, 99, '/sites/bee-stitch/bee-stitch.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('brand-mood', 'Brand Mood', 'other', 'available', 0, 99, '/sites/brand-mood/brand-mood.png');
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('calendars-unite', 'Calendars Unite', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('candle-light-the-mood', 'Candle Light The Mood', 'food/bev', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('canvas-current', 'Canvas Current', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('card-decks', 'Card Decks', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('carpet-palace', 'Carpet Palace', 'services', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('cars-beyond', 'Cars Beyond', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('casino-time', 'Casino Time', 'finance', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('celebrities-around', 'Celebrities Around', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('ceramic-factory', 'Ceramic Factory', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('christmas-home-glow', 'Christmas Home Glow', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('cinema-rush', 'Cinema Rush', 'creative', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('cinematic-caves', 'Cinematic Caves', 'creative', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('circus-is-here', 'Circus Is Here', 'creative', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('clean-sweep', 'Clean Sweep', 'services', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('coffee-please', 'Coffee Please', 'food/bev', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('comedy-clubs-open', 'Comedy Clubs Open', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('construction-junction', 'Construction Junction', 'services', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('cornhole-fun', 'Cornhole Fun', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('cosmetic-glam-vibe', 'Cosmetic Glam Vibe', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('cosmic-visuals', 'Cosmic Visuals', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('criminal-attorney', 'Criminal Attorney', 'legal', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('daily-prompts', 'Daily Prompts', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('deep-sea-diving', 'Deep Sea Diving', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('demolition-services', 'Demolition Services', 'services', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('dental-office-with-glow', 'Dental Office With Glow', 'health', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('dessert-ebook', 'Dessert Ebook', 'food/bev', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('digital-art-vault', 'Digital Art Vault', 'creative', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('digital-product-experience', 'Digital Product Experience', 'creative', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('digital-product-experience-v2', 'Digital Product Experience V2', 'creative', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('digital-stickers', 'Digital Stickers', 'creative', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('dog-memorial-ecards', 'Dog Memorial Ecards', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('dogs-who-are-calm', 'Dogs Who Are Calm', 'health', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('doll-house', 'Doll House', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('elegant-french-restraurant', 'Elegant French Restraurant', 'other', 'available', 0, 99, NULL);
INSERT OR IGNORE INTO wlvlp_templates (slug, title, category, status, vote_count, buy_now_price, thumbnail_url) VALUES ('event-posters', 'Event Posters', 'other', 'available', 0, 99, NULL);
